<template>
  <div class="text-center">
    <svg class="inline-block w-5 h-5" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="margin: auto; background: none; display: block; shape-rendering: auto;" width="200px" height="200px" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid">
      <circle :class="strokeClass" cx="50" cy="50" fill="none" stroke="#bee3f8" stroke-width="8" r="35" stroke-dasharray="164.93361431346415 56.97787143782138">
        <animateTransform attributeName="transform" type="rotate" repeatCount="indefinite" dur="1s" values="0 50 50;360 50 50" keyTimes="0;1"></animateTransform>
      </circle>
    <!-- [ldio] generated by https://loading.io/ --></svg>
  </div>
</template>

<script setup>
import { defineProps, toRefs } from 'vue'

const props = defineProps({
  strokeClass: {
    type: String,
    default: ''
  }
})

const { strokeClass } = toRefs(props)
</script>
